### ISSUE TITLE
Migration Refresh On Dev

### ISSUE THREAD

**Issue by matyhaty** [antonioribeiro/tracker#57] opened 2015-01-07 16:33 UTC
If you have allowed logging on local IPs (127.0.0.xxx etc) and try and do a Migration, it will fail.

I assume its cause its trying to log things which are not ready yet.
Although not a major problem, really it should be hard coded in, that if its migrating - all logging is disabled - even tho logging is on (as per installation instructions)

**Comment by antonioribeiro** [comment] 2015-02-23 18:39
Well, I commented it:

	'do_not_track_ips' => [
		// '127.0.0.0/24' /// range 127.0.0.1 - 127.0.0.255
	],

Then did a `migrate:refresh` and it worked :(

	 $ a migrate:refresh
	Artisan found at /var/www/tests/l4/artisan
	**************************************
	*     Application In Production!     *
	**************************************

	Do you really wish to run this command? y
	**************************************
	*     Application In Production!     *
	**************************************

	Do you really wish to run this command? y
	Rolled back: 2015_02_23_183505_create_dummy_table
	Rolled back: 2015_02_23_174214_create_users_table
	Rolled back: 2015_02_23_173501_create_tracker_tables
	Nothing to rollback.
	**************************************
	*     Application In Production!     *
	**************************************

	Do you really wish to run this command? y
	Migrated: 2015_02_23_173501_create_tracker_tables
	Migrated: 2015_02_23_174214_create_users_table
	Migrated: 2015_02_23_183505_create_dummy_table

Could you, please, help me reproduce it?

**Comment by matyhaty** [comment] 2015-02-23 18:45
Did you run any seeding?

**Comment by antonioribeiro** [comment] 2015-02-23 19:15
No seeding.

**Comment by antonioribeiro** [comment] 2015-02-23 19:19
I understand ´migrate:refresh´ could be a problem, because it does a ´migrate:reset´, which is supposed to drop all tables and having no tables it would raise an exception while trying to insert on them. Seeding comes after ´migrate´, it should not be a problem.

**Comment by antonioribeiro** [comment] 2015-02-25 18:04
Closing for now, if you still need support, ask for a reopening. Thank you.

**Closed by antonioribeiro** 2015-02-25 18:04 UTC
